### PR TITLE
Avoid partial argument name match in legend()

### LINKED ISSUE #339: partial argument matching
` y.inter=` should be ` y.intersp=` in call to `legend()`
https://github.com/joshuaulrich/quantmod/search?q=y.inter

### PR DESCRIPTION
**Pull request by ethanbsmith**
Fixes #339.

### CODE REVIEW

**Comment by joshuaulrich** [comment]
Thanks! How did you find all of these?

**Comment by ethanbsmith** [comment]
options(warnPartialMatchArgs = TRUE)
options(warn=2)

i was looking for issues in my code and ran into these.  probably covered a decent chunk of xts, ttr and quantmod
________________________________

**Comment by joshuaulrich** [comment]
Sorry, I assumed you had that set. I'm looking for a reproducible example that triggers the warning.

FWIW, I have these options set:

```
warnPartialMatchArgs = TRUE,
warnPartialMatchAttr = TRUE,
warnPartialMatchDollar = TRUE,
```

**Comment by ethanbsmith** [comment]
gotcha. ill dig through my code and find whats triggering it. ill add that info back to the underlying issue
________________________________

**Comment by joshuaulrich** [comment]
Awesome. No rush. Just thought it would be nice to have a unit test.

**Pull request merged**
