### PR TITLE
Update getQuote.R

### PR DESCRIPTION
**Pull request by ethanbsmith**
added support for AV batch quotes by extending getQuote with getQuote.av

### CODE REVIEW

**Comment by ethanbsmith** [comment]
fixes #213

**Comment by ethanbsmith** [comment]
@joshuaulrich Im still new at this whole github thing, but it looks to me like the CI test is failing on a google getSymbols call. At this point Im not sure what to do, so will wait for your input. thx.

**Comment by joshuaulrich** [comment]
It's not you, it's Google.  I'll re-run this build.

**Comment by joshuaulrich** [comment]
@ethanbsmith can you please give me permission to push to this PR branch?  See, "[Allowing changes to a pull request branch created from a fork](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)".

You branched from the commit after v0.4-11, so I have rebased the branch and squashed the 3 commits. We can close this PR as "merged" if I can push to the PR branch, but will be marked as "closed" if I merge my local branch.

**Comment by ethanbsmith** [comment]
should be good. let me know if u need anything else

**Pull request merged**
