### PR TITLE
used full name

### LINKED ISSUE #348: partial match in TA.R
image

line 28 should be `lengths`, not `length`

### PR DESCRIPTION
**Pull request by ethanbsmith**
used full variable names. fixes #348

### CODE REVIEW

**Comment by joshuaulrich** [comment]
Thanks for the fix! No need to make an issue and PR for something simple like a typo. You only need to create an issue first if you're not sure whether it's actually an issue and/or you're not sure the best way to fix it.

**Comment by joshuaulrich** [comment]
I just noticed that there's another partial match on the same line:

```r
start = cumsum(runs$lengths)[which(runs$values)] - runs$length(((s)))[which(runs$values)]+1,
```

Can you make that change too? I tried to, but I can't push to your branch.

**Comment by ethanbsmith** [comment]
done

**Comment by joshuaulrich** [comment]
Thanks!

**Pull request merged**
